
import __ASTRO_IMAGE_IMPORT_ZWbOge from "../../assets/covers/200-pytan-do-chlopaka.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2F200-pytan-do-chlopaka.md";
import __ASTRO_IMAGE_IMPORT_ZXOz7U from "../../assets/covers/200-pytan-do-dziewczyny.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2F200-pytan-do-dziewczyny.md";
import __ASTRO_IMAGE_IMPORT_95TE8 from "../../assets/covers/dotyk-i-lod.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fdotyk-i-lod-emanacja-mocy.md";
import __ASTRO_IMAGE_IMPORT_8jNDs from "../../assets/covers/fraszki-frywolne.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Ffraszki-frywolne.md";
import __ASTRO_IMAGE_IMPORT_ZJwIvl from "../../assets/covers/grunwald-1410.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fgrunwald-1410.md";
import __ASTRO_IMAGE_IMPORT_2hdlMQ from "../../assets/covers/grzeskowe-bajanie-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fgrzeskowe-bajanie-1.md";
import __ASTRO_IMAGE_IMPORT_Z1mIY5p from "../../assets/covers/grzeskowe-bajanie-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fgrzeskowe-bajanie-2.md";
import __ASTRO_IMAGE_IMPORT_ZgB8pP from "../../assets/covers/hiszpanskie-noce.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fhiszpanskie-noce.md";
import __ASTRO_IMAGE_IMPORT_mpU1p from "../../assets/covers/kobieta-w-worku.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fkobieta-w-worku.md";
import __ASTRO_IMAGE_IMPORT_Z1886Fl from "../../assets/covers/kroniki-t1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fkroniki-bursztynowego-plynu-t1.md";
import __ASTRO_IMAGE_IMPORT_Zkk6FW from "../../assets/covers/kroniki-t2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fkroniki-bursztynowego-plynu-t2.md";
import __ASTRO_IMAGE_IMPORT_ssSir from "../../assets/covers/kroniki-t3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fkroniki-bursztynowego-plynu-t3.md";
import __ASTRO_IMAGE_IMPORT_2x0iqv from "../../assets/covers/morderstwo-w-domu.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fmorderstwo-w-domu-wagnerow.md";
import __ASTRO_IMAGE_IMPORT_Z1SDUeD from "../../assets/covers/placeholder-cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fprzygody-odwaznego-kapturka.md";
import __ASTRO_IMAGE_IMPORT_ZnehdW from "../../assets/covers/warsaw-z.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fwarsaw-z.md";
import __ASTRO_IMAGE_IMPORT_Z2bkh2U from "../../assets/covers/placeholder-cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fromans-tytul-roboczy.md";
import __ASTRO_IMAGE_IMPORT_Z1kACp7 from "../../assets/covers/dotyk-i-lod.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fdotyk-i-lod-emanacja-mocy+copy.md";
import __ASTRO_IMAGE_IMPORT_b4uO from "../../assets/covers/dotyk-i-lod.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fprotokol-i-szept.md";
import __ASTRO_IMAGE_IMPORT_1ftWb1 from "../../assets/covers/protokol-i-szept.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fprotokol-i-szept.md";
export default new Map([["../../assets/covers/200-pytan-do-chlopaka.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2F200-pytan-do-chlopaka.md", __ASTRO_IMAGE_IMPORT_ZWbOge], ["../../assets/covers/200-pytan-do-dziewczyny.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2F200-pytan-do-dziewczyny.md", __ASTRO_IMAGE_IMPORT_ZXOz7U], ["../../assets/covers/dotyk-i-lod.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fdotyk-i-lod-emanacja-mocy.md", __ASTRO_IMAGE_IMPORT_95TE8], ["../../assets/covers/fraszki-frywolne.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Ffraszki-frywolne.md", __ASTRO_IMAGE_IMPORT_8jNDs], ["../../assets/covers/grunwald-1410.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fgrunwald-1410.md", __ASTRO_IMAGE_IMPORT_ZJwIvl], ["../../assets/covers/grzeskowe-bajanie-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fgrzeskowe-bajanie-1.md", __ASTRO_IMAGE_IMPORT_2hdlMQ], ["../../assets/covers/grzeskowe-bajanie-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fgrzeskowe-bajanie-2.md", __ASTRO_IMAGE_IMPORT_Z1mIY5p], ["../../assets/covers/hiszpanskie-noce.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fhiszpanskie-noce.md", __ASTRO_IMAGE_IMPORT_ZgB8pP], ["../../assets/covers/kobieta-w-worku.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fkobieta-w-worku.md", __ASTRO_IMAGE_IMPORT_mpU1p], ["../../assets/covers/kroniki-t1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fkroniki-bursztynowego-plynu-t1.md", __ASTRO_IMAGE_IMPORT_Z1886Fl], ["../../assets/covers/kroniki-t2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fkroniki-bursztynowego-plynu-t2.md", __ASTRO_IMAGE_IMPORT_Zkk6FW], ["../../assets/covers/kroniki-t3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fkroniki-bursztynowego-plynu-t3.md", __ASTRO_IMAGE_IMPORT_ssSir], ["../../assets/covers/morderstwo-w-domu.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fmorderstwo-w-domu-wagnerow.md", __ASTRO_IMAGE_IMPORT_2x0iqv], ["../../assets/covers/placeholder-cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fprzygody-odwaznego-kapturka.md", __ASTRO_IMAGE_IMPORT_Z1SDUeD], ["../../assets/covers/warsaw-z.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fwarsaw-z.md", __ASTRO_IMAGE_IMPORT_ZnehdW], ["../../assets/covers/placeholder-cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fromans-tytul-roboczy.md", __ASTRO_IMAGE_IMPORT_Z2bkh2U], ["../../assets/covers/dotyk-i-lod.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fdotyk-i-lod-emanacja-mocy+copy.md", __ASTRO_IMAGE_IMPORT_Z1kACp7], ["../../assets/covers/dotyk-i-lod.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fprotokol-i-szept.md", __ASTRO_IMAGE_IMPORT_b4uO], ["../../assets/covers/protokol-i-szept.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fprotokol-i-szept.md", __ASTRO_IMAGE_IMPORT_1ftWb1]]);
		