
import __ASTRO_IMAGE_IMPORT_ZXOz7U from "../../assets/covers/200-pytan-do-dziewczyny.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2F200-pytan-do-dziewczyny.md";
import __ASTRO_IMAGE_IMPORT_ZWbOge from "../../assets/covers/200-pytan-do-chlopaka.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2F200-pytan-do-chlopaka.md";
import __ASTRO_IMAGE_IMPORT_8jNDs from "../../assets/covers/fraszki-frywolne.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Ffraszki-frywolne.md";
import __ASTRO_IMAGE_IMPORT_ZJwIvl from "../../assets/covers/grunwald-1410.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fgrunwald-1410.md";
import __ASTRO_IMAGE_IMPORT_2hdlMQ from "../../assets/covers/grzeskowe-bajanie-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fgrzeskowe-bajanie-1.md";
import __ASTRO_IMAGE_IMPORT_ZgB8pP from "../../assets/covers/hiszpanskie-noce.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fhiszpanskie-noce.md";
import __ASTRO_IMAGE_IMPORT_Z1mIY5p from "../../assets/covers/grzeskowe-bajanie-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fgrzeskowe-bajanie-2.md";
import __ASTRO_IMAGE_IMPORT_2x0iqv from "../../assets/covers/morderstwo-w-domu.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fmorderstwo-w-domu-wagnerow.md";
import __ASTRO_IMAGE_IMPORT_mpU1p from "../../assets/covers/kobieta-w-worku.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fkobieta-w-worku.md";
import __ASTRO_IMAGE_IMPORT_Z1SDUeD from "../../assets/covers/placeholder-cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fprzygody-odwaznego-kapturka.md";
import __ASTRO_IMAGE_IMPORT_Z2bkh2U from "../../assets/covers/placeholder-cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fromans-tytul-roboczy.md";
import __ASTRO_IMAGE_IMPORT_2n3Ww6 from "../../assets/covers/placeholder-cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fromantasy-tytul-roboczy.md";
import __ASTRO_IMAGE_IMPORT_ZnehdW from "../../assets/covers/warsaw-z.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fwarsaw-z.md";
export default new Map([["../../assets/covers/200-pytan-do-dziewczyny.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2F200-pytan-do-dziewczyny.md", __ASTRO_IMAGE_IMPORT_ZXOz7U], ["../../assets/covers/200-pytan-do-chlopaka.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2F200-pytan-do-chlopaka.md", __ASTRO_IMAGE_IMPORT_ZWbOge], ["../../assets/covers/fraszki-frywolne.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Ffraszki-frywolne.md", __ASTRO_IMAGE_IMPORT_8jNDs], ["../../assets/covers/grunwald-1410.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fgrunwald-1410.md", __ASTRO_IMAGE_IMPORT_ZJwIvl], ["../../assets/covers/grzeskowe-bajanie-1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fgrzeskowe-bajanie-1.md", __ASTRO_IMAGE_IMPORT_2hdlMQ], ["../../assets/covers/hiszpanskie-noce.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fhiszpanskie-noce.md", __ASTRO_IMAGE_IMPORT_ZgB8pP], ["../../assets/covers/grzeskowe-bajanie-2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fgrzeskowe-bajanie-2.md", __ASTRO_IMAGE_IMPORT_Z1mIY5p], ["../../assets/covers/morderstwo-w-domu.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fmorderstwo-w-domu-wagnerow.md", __ASTRO_IMAGE_IMPORT_2x0iqv], ["../../assets/covers/kobieta-w-worku.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fkobieta-w-worku.md", __ASTRO_IMAGE_IMPORT_mpU1p], ["../../assets/covers/placeholder-cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fprzygody-odwaznego-kapturka.md", __ASTRO_IMAGE_IMPORT_Z1SDUeD], ["../../assets/covers/placeholder-cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fromans-tytul-roboczy.md", __ASTRO_IMAGE_IMPORT_Z2bkh2U], ["../../assets/covers/placeholder-cover.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fromantasy-tytul-roboczy.md", __ASTRO_IMAGE_IMPORT_2n3Ww6], ["../../assets/covers/warsaw-z.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fbooks%2Fwarsaw-z.md", __ASTRO_IMAGE_IMPORT_ZnehdW]]);
		